no need to fetch changes if we just cloned the repository

diff --git a/decomposer b/decomposer
--- a/decomposer
+++ b/decomposer
@@ -46,6 +46,8 @@ decomposer_install_library() {
       printf -v "${status_text_variable}" 'cloning git repository failed'
       return 1
     fi
+
+    local just_cloned=1
   fi
 
   if [ -h "${name}-${version}" ]; then
@@ -61,9 +63,12 @@ decomposer_install_library() {
 
   cd "${library_target_dir}"
 
-  if ! git fetch origin &> /dev/null; then
-    printf -v "${status_text_variable}" 'fetching changes failed'
-    return 1
+  if [ -z "${just_cloned}" ]; then
+    # no need to fetch changes if we just cloned the repository
+    if ! git fetch origin &> /dev/null; then
+      printf -v "${status_text_variable}" 'fetching changes failed'
+      return 1
+    fi
   fi
 
   if [ "$( jq 'has("revision")' <<< "${object}" )" = 'true' ]; then
