Avoid running git fetch if not needed

diff --git a/decomposer b/decomposer
--- a/decomposer
+++ b/decomposer
@@ -67,19 +67,10 @@ decomposer_install_library() {
 
   cd "${library_target_dir}" || return 2
 
-  if [ -z "${just_cloned}" ]; then
-    # no need to fetch changes if we just cloned the repository
-    if ! git fetch origin &> /dev/null; then
-      printf -v "${status_text_variable}" 'fetching changes failed'
-      return 1
-    fi
-  fi
-
   local revision revision_type revision_alt_type revision_reset
 
-  if [ "$( jq 'has("revision")' <<< "${object}" )" = 'true' ]; then
-    revision=$( jq -r '.revision' <<< "${object}" )
-  else
+  revision=$( jq -r '.revision' <<< "${object}" )
+  if [ "${revision}" = "null" ]; then
     revision="${version}"
   fi
 
@@ -93,6 +84,29 @@ decomposer_install_library() {
     revision_reset="${revision}"
   elif [ "${revision_alt_type}" = 'commit' ] || [ "${revision_alt_type}" = 'tag' ]; then
     revision_reset="v${revision}"
+  fi
+
+  if [ -z "${just_cloned}" ] && [ "${revision_reset}" = "origin/${revision}" ] || [ -z "${revision_reset}" ]; then
+    # no need to fetch changes if we just cloned the repository
+    # or we can already resolve a commit or tag
+    if ! git fetch origin &> /dev/null; then
+      printf -v "${status_text_variable}" 'fetching changes failed'
+      return 1
+    fi
+  fi
+
+  if [ -z "$revision_reset" ]; then
+    revision_type=$( git cat-file -t "${revision}" 2> /dev/null )
+    revision_alt_type=$( git cat-file -t "v${revision}" 2> /dev/null )
+    revision_reset=
+
+    if git branch -a | grep -q "/origin/${revision}"; then
+      revision_reset="origin/${revision}"
+    elif [ "${revision_type}" = 'commit' ] || [ "${revision_type}" = 'tag' ]; then
+      revision_reset="${revision}"
+    elif [ "${revision_alt_type}" = 'commit' ] || [ "${revision_alt_type}" = 'tag' ]; then
+      revision_reset="v${revision}"
+    fi
   fi
 
   if [ -z "${revision_reset}" ]; then
